"use client";

import { motion, useReducedMotion } from "framer-motion";
import { Camera, Heart, Mail, Moon, Sparkles } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const experiences = [
  { href: "/october-2", label: "02.10", title: "The evening it all began", detail: "The day I first saw you. ❤️", icon: Moon, accent: "wine" },
  { href: "/mood-booster", label: "For you", title: "Open when you need me", detail: "Your personal little mood fixer. ❤️", icon: Mail, accent: "magenta" },
  { href: "/memories", label: "Our memories", title: "Little pieces of us", detail: "The moments I don't want to forget. ❤️", icon: Camera, accent: "cream" },
  { href: "/just-because", label: "Just because", title: "A tiny surprise", detail: "No reason. Just you. 💗", icon: Sparkles, accent: "rose" },
];

export function NinaHome() {
  const reduceMotion = useReducedMotion();
  const [secretClicks, setSecretClicks] = useState(0);
  return <main className="relative min-h-screen overflow-hidden bg-warm-white px-5 py-8 text-cocoa sm:px-8"><AmbientBackground /><div className="relative z-10 mx-auto max-w-6xl"><header className="text-center"><motion.p className="font-serif text-xl italic text-deep-red/80 sm:text-2xl" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.7 }}>I made you a little place...</motion.p><motion.h1 className="mt-3 font-serif text-5xl font-semibold leading-none text-cocoa sm:text-7xl" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: reduceMotion ? 0 : 0.18, duration: 0.65 }}>Nina<span className="text-nina-red">. ❤️</span></motion.h1><motion.p className="mx-auto mt-5 max-w-md text-base font-medium leading-relaxed text-plum sm:text-lg" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: reduceMotion ? 0 : 0.38 }}>Come in. There&apos;s a little bit of us waiting inside.</motion.p></header><section className="relative mx-auto mt-10 grid max-w-5xl items-center gap-5 lg:min-h-[470px] lg:grid-cols-[1fr_1.08fr_1fr]" aria-label="Nina's experiences"><div className="order-2 grid gap-4 lg:order-1">{experiences.slice(0, 2).map((experience, index) => <ExperienceBubble key={experience.href} experience={experience} index={index} />)}</div><PhotoFrame onSecret={() => setSecretClicks((count) => count + 1)} secretClicks={secretClicks} /><div className="order-3 grid gap-4">{experiences.slice(2).map((experience, index) => <ExperienceBubble key={experience.href} experience={experience} index={index + 2} />)}</div></section><motion.p className="mt-10 text-center text-sm font-medium italic text-plum/80" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: reduceMotion ? 0 : 0.8 }}>Made with an unreasonable amount of thought. ❤️</motion.p><p className="mt-2 text-center text-xs font-medium text-gold">Please explore responsibly. ✨</p></div></main>;
}

function PhotoFrame({ onSecret, secretClicks }: { onSecret: () => void; secretClicks: number }) {
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  return <motion.section className="order-1 mx-auto w-full max-w-sm lg:order-2 lg:max-w-md" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.3, duration: 0.7 }} onMouseMove={(event) => { const rect = event.currentTarget.getBoundingClientRect(); setTilt({ x: (event.clientX - rect.left - rect.width / 2) / 35, y: (event.clientY - rect.top - rect.height / 2) / 35 }); }} onMouseLeave={() => setTilt({ x: 0, y: 0 })}><motion.div className="relative rotate-[-2deg] border border-deep-red/40 bg-[#fff9f4] p-3 pb-10 shadow-[0_28px_55px_rgba(74,22,53,0.2)]" animate={{ rotateX: -tilt.y, rotateY: tilt.x, y: [0, -4, 0] }} transition={{ y: { repeat: Infinity, duration: 4.5, ease: "easeInOut" }, rotateX: { type: "spring", stiffness: 110, damping: 18 }, rotateY: { type: "spring", stiffness: 110, damping: 18 } }}><span className="absolute right-3 top-3 z-10 h-2 w-2 rounded-full bg-gold shadow-[0_0_10px_rgba(181,138,69,0.8)]" /><div className="grid aspect-[4/5] place-items-center overflow-hidden border border-gold/30 bg-[linear-gradient(135deg,#f3dce5,#e7b6c7_45%,#fff0e6)] p-8 text-center"><div><Heart className="mx-auto h-9 w-9 text-nina-red" fill="currentColor" /><p className="mt-4 font-serif text-3xl italic text-deep-red">A place for your photo</p><p className="mt-3 text-sm font-medium text-plum">Add one in <code>public/images/nina-home.jpg</code></p><p className="mt-5 text-xs font-medium italic text-deep-red/75">My favourite view. ❤️</p></div></div><button type="button" onClick={onSecret} aria-label="A small heart in the photo corner" className="absolute bottom-3 right-3 text-nina-red/65 outline-none transition hover:scale-110 focus-visible:ring-4 focus-visible:ring-nina-red/30"><Heart className="h-4 w-4" fill="currentColor" /></button><p className="absolute bottom-3 left-4 font-serif text-lg italic text-deep-red/80">just you.</p></motion.div>{secretClicks >= 3 ? <motion.p initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="mx-auto mt-4 max-w-xs text-center text-sm font-medium text-plum">You found something you&apos;re probably not supposed to find. There may or may not be more secrets here. ✨</motion.p> : null}</motion.section>;
}

function ExperienceBubble({ experience, index }: { experience: (typeof experiences)[number]; index: number }) {
  const Icon = experience.icon;
  const accent = experience.accent === "magenta" ? "border-nina-green/30 bg-[#f3dbe5] hover:border-nina-green/60" : experience.accent === "wine" ? "border-deep-red/35 bg-[#f4dfe8] hover:border-nina-red/70" : experience.accent === "rose" ? "border-gold/30 bg-[#f8e8ee] hover:border-deep-red/50" : "border-champagne bg-[#fff9f4] hover:border-nina-green/40";
  return <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.46 + index * 0.1 }} whileHover={{ y: -4, scale: 1.015 }}><Link href={experience.href} className={`group relative block overflow-hidden rounded-lg border p-5 shadow-[0_14px_30px_rgba(74,22,53,0.1)] outline-none transition focus-visible:ring-4 focus-visible:ring-nina-red/25 ${accent}`}><span className="absolute right-4 top-3 text-gold/70">✦</span><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white/75 text-deep-red shadow-sm transition group-hover:rotate-6"><Icon className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-deep-red/70">{experience.label}</p><h2 className="mt-1 font-serif text-xl font-semibold leading-tight text-cocoa">{experience.title}</h2><p className="mt-2 text-sm font-medium leading-relaxed text-plum">{experience.detail}</p><span className="mt-3 inline-block text-xs font-bold text-nina-green transition group-hover:translate-x-1">open →</span></div></div></Link></motion.div>;
}

function AmbientBackground() {
  const reduceMotion = useReducedMotion();
  return <div aria-hidden="true" className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_15%,rgba(231,182,199,0.54),transparent_32%),radial-gradient(circle_at_80%_70%,rgba(232,210,176,0.38),transparent_30%)]" />{Array.from({ length: 11 }).map((_, index) => <motion.span key={index} className="absolute h-1 w-1 rounded-full bg-gold/65" style={{ left: `${7 + ((index * 23) % 84)}%`, top: `${10 + ((index * 17) % 78)}%` }} animate={reduceMotion ? undefined : { y: [0, -10, 0], opacity: [0.25, 0.7, 0.25] }} transition={{ duration: 4 + (index % 3), repeat: Infinity, delay: index * 0.2 }} />)}</div>;
}
